# Copyright 2018, 2019 the Velero contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG target
FROM golang:1.13 as builder

ARG goarch
ENV GOOS linux
ENV GOARCH $goarch
ENV CGO_ENABLED 0

ENV IMAGE heptio/velero
WORKDIR /go/src/github.com/${IMAGE}

RUN \
  git clone --depth=1 https://github.com/${IMAGE} . && \
  go build -o /velero-restic-restore-helper cmd/velero-restic-restore-helper/main.go

# ==================
# Final stage.
# ==================
FROM $target/ubuntu:disco

COPY qemu-* /usr/bin/

RUN mkdir /restores && chmod 0755 /restores

LABEL maintainer="Jesse Stuart <hi@jessestuart.com>"

COPY --from=builder /velero-restic-restore-helper /velero-restic-restore-helper

USER nobody:nogroup

ENTRYPOINT [ "/velero-restic-restore-helper" ]
