# Copyright 2018, 2019 the Velero contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG target
FROM golang:1.12 as builder

ARG goarch
ENV GOOS linux
ENV GOARCH $goarch
ENV CGO_ENABLED 0

ENV image heptio/velero
WORKDIR /go/src/github.com/${image}

RUN \
  git clone --depth=1 https://github.com/${image} . && \
  go build -o /bin/velero-restic-restore-helper cmd/velero-restic-restore-helper/main.go

# # ==================
# # Final stage.
# # ==================
# FROM $target/alpine

# LABEL maintainer="Jesse Stuart <hi@jessestuart.com>"

# COPY qemu-* /usr/bin/
# COPY --from=builder /velero /velero

# ARG goarch
# ADD https://github.com/restic/restic/releases/download/v0.9.5/restic_0.9.5_linux_${goarch}.bz2 /restic.bz2
# RUN apk add --no-cache --update ca-certificates && \
#   bunzip2 restic.bz2 && \
#   chmod +x /restic && \
#   mv /restic /usr/bin/restic

# USER nobody:nobody

# ENTRYPOINT ["/velero"]

# ARG target
FROM $target/ubuntu:disco

COPY qemu-* /usr/bin/

LABEL maintainer="Jesse Stuart <hi@jessestuart.com>"

COPY --from=builder /bin/velero-restic-restore-helper /bin/velero-restic-restore-helper

USER nobody

ENTRYPOINT [ "/bin/velero-restic-restore-helper" ]
